dotnet2/Models/ErrorViewModel.cs
namespace dotnet2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

dotnet2/Models/collegeDepartmentModel.cs
namespace collegemanagementfirstproject.Models
{
    public class collegeDepartmentModel
    {
        public int DepartmentId { get; set; }

        public string? DepartmentName { get; set; }

        public string? DepartmentHead { get; set; }

        public string? OfficeLocation{ get; set; }

        public string? ContactEmail { get; set; }

        public string? CreatedAt { get; set; }
       




    }
}

dotnet2/Models/collegeFacultymodel.cs
namespace collegemanagementfirstproject.Models
{
    public class collegeFacultymodel
    {
        public int FacultyID { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? Email { get; set; }
        public string? PhoneNumber { get; set; }
        public string? Department { get; set; }
        public  string? HireDate { get; set; }
       
        public string? Designation { get; set; }
        

    }
}

dotnet2/Models/collegestudentModel.cs
namespace collegemanagementfirstproject.Models
{
    public class collegestudentModel

    {
        public int Id { get; set; }
        public string ? Name { get; set; }

        public  string? Email { get; set; }
      
        
    }
}

dotnet2/Controllers/HomeController.cs
using System.Diagnostics;
using dotnet2.Models;
using Microsoft.AspNetCore.Mvc;

namespace dotnet2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

dotnet2/Controllers/collegeDepartmentController.cs
using collegemanagementfirstproject.Interface;
using collegemanagementfirstproject.Models;
using Microsoft.AspNetCore.Mvc;

namespace collegemanagementfirstproject.Controllers
{
    public class collegeDepartmentController : Controller
    {
        private readonly Icollegedepart _cdepartRepo;


        public collegeDepartmentController(Icollegedepart cdepart)
        {
            _cdepartRepo = cdepart;
        }
        public IActionResult Index()
        {
            IEnumerable<collegeDepartmentModel> cdepart = _cdepartRepo.GetAllcollegeDepartment();
            return View(cdepart);
        }

        [HttpGet]
        public IActionResult AddcollegeDepartment()
        {
            return View();
        }
        [HttpPost]

        public ActionResult AddcollegeDepartment(collegeDepartmentModel cd)
        {

            _cdepartRepo.InsertcollegeDepartment(cd);
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public IActionResult EditcollegeDepartment(int id)
        {
            var cdepart = _cdepartRepo.GetById(id);
            return View(cdepart);
        }
        [HttpPost]

        public ActionResult EditcollegeDepartment(collegeDepartmentModel cd)
        {
            _cdepartRepo.UpdatecollegeDepartment(cd);
            return RedirectToAction(nameof(Index));
        }





        [HttpGet]
        public IActionResult DeletecollegeDepartment(int check)
        {
            var cdepart = _cdepartRepo.GetById(check);
            return View(cdepart);
        }
        [HttpPost]

        public ActionResult DeletecollegeDepartment(collegeDepartmentModel test)
        {
            _cdepartRepo.DeletecollegeDepartment(test);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult DetailcollegeDepartment(int fact)
        {
            var cdepart = _cdepartRepo.GetById(fact);
            return View(cdepart);
        }
    }
}

dotnet2/Controllers/collegestudentController.cs
using collegemanagementfirstproject.Interface;
using collegemanagementfirstproject.Models;
using Humanizer.Localisation.TimeToClockNotation;
using Microsoft.AspNetCore.Mvc;

namespace collegemanagementfirstproject.Controllers
{
    public class collegestudentController : Controller
    {
        private readonly Icollegestudent _cstudentRepo;

        public collegestudentController(Icollegestudent cstudent)
        {
            _cstudentRepo = cstudent;
        }
        public IActionResult Index()
        {
            IEnumerable<collegestudentModel> cstudent =_cstudentRepo.GetAllcollegestudent(); 
            return View(cstudent);
        }
   
        [HttpGet]
        public IActionResult Addcollegestudent()
        {
            return View();
        }
        [HttpPost]

        public ActionResult Addcollegestudent(collegestudentModel  cs)
        {
            _cstudentRepo.Insertcollegestudent(cs);
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public IActionResult Editcollegestudent( int id)
        {
            var cstudent =_cstudentRepo.GetById(id);
            return View(cstudent);
        }
        [HttpPost]

        public ActionResult Editcollegestudent(collegestudentModel cs)
        {
            _cstudentRepo.Updatecollegestudent(cs);
            return RedirectToAction(nameof(Index));
        }


       
       

        [HttpGet]
        public IActionResult Deletecollegestudent(int test)
        {
            var cstudent = _cstudentRepo.GetById(test);
            return View(cstudent);
        }
        [HttpPost]

        public ActionResult Deletecollegestudent(collegestudentModel test)
        {
            _cstudentRepo.Deletecollegestudent(test);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Detailcollegestudent(int id)
        {
            var cstudent = _cstudentRepo.GetById(id);
            return View(cstudent);
        }
    }
} 

dotnet2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

dotnet2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotnet2</title>
     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> 
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/dotnet2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dotnet2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="collegestudent" asp-action="index">collegestudent</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="collegeDepartment" asp-action="index">collegeDepart</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="collegeFaculty" asp-action="IndexforJs">collegeFaculty</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - dotnet2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

dotnet2/Views/collegeDepartment/AddcollegeDepartment.cshtml
@model collegemanagementfirstproject.Models.collegeDepartmentModel

@{
    ViewData["Title"] = "AddcollegeDepartment";
}

<h1>AddcollegeDepartment</h1>

<h4>collegeDepartmentModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddcollegeDepartment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentHead" class="control-label"></label>
                <input asp-for="DepartmentHead" class="form-control" />
                <span asp-validation-for="DepartmentHead" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeLocation" class="control-label"></label>
                <input asp-for="OfficeLocation" class="form-control" />
                <span asp-validation-for="OfficeLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactEmail" class="control-label"></label>
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

dotnet2/Views/collegeDepartment/DeletecollegeDepartment.cshtml
@model collegemanagementfirstproject.Models.collegeDepartmentModel

@{
    ViewData["Title"] = "DeletecollegeDepartment";
}

<h1>DeletecollegeDepartment</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>collegeDepartmentModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentHead)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentHead)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficeLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficeLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
    
    <form asp-action="DeletecollegeDepartment">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

dotnet2/Views/collegeDepartment/DetailcollegeDepartment.cshtml
@model collegemanagementfirstproject.Models.collegeDepartmentModel

@{
    ViewData["Title"] = "DetailcollegeDepartment";
}

<h1>DetailcollegeDepartment</h1>

<div>
    <h4>collegeDepartmentModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentHead)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepartmentHead)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficeLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficeLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

dotnet2/Views/collegeDepartment/EditcollegeDepartment.cshtml
@model collegemanagementfirstproject.Models.collegeDepartmentModel

@{
    ViewData["Title"] = "EditcollegeDepartment";
}

<h1>EditcollegeDepartment</h1>

<h4>collegeDepartmentModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditcollegeDepartment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <input asp-for="DepartmentId" class="form-control" />
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentHead" class="control-label"></label>
                <input asp-for="DepartmentHead" class="form-control" />
                <span asp-validation-for="DepartmentHead" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeLocation" class="control-label"></label>
                <input asp-for="OfficeLocation" class="form-control" />
                <span asp-validation-for="OfficeLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactEmail" class="control-label"></label>
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

dotnet2/Views/collegeDepartment/Index.cshtml
@model IEnumerable<collegemanagementfirstproject.Models.collegeDepartmentModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="AddcollegeDepartment">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentHead)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OfficeLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentHead)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfficeLocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                    @Html.ActionLink("Edit", "EditcollegeDepartment", new { id = item.DepartmentId }) |
                    @Html.ActionLink("Detail", "DetailcollegeDepartment", new { fact = item.DepartmentId }) |
                    @Html.ActionLink("Delete", "DeletecollegeDepartment", new { check = item.DepartmentId })
            </td>
        </tr>
}
    </tbody>
</table>

dotnet2/Views/collegeFaculty/AddcollegeFaculty.cshtml
@model collegemanagementfirstproject.Models.collegeFacultymodel

@{
    ViewData["Title"] = "AddcollegeFaculty";
}

<h1>AddcollegeFaculty</h1>

<h4>collegeFacultymodel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddcollegeFaculty">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Designation" class="control-label"></label>
                <input asp-for="Designation" class="form-control" />
                <span asp-validation-for="Designation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

dotnet2/Views/collegeFaculty/DeletecollegeFaculty.cshtml
@model collegemanagementfirstproject.Models.collegeFacultymodel

@{
    ViewData["Title"] = "DeletecollegeFaculty";
}

<h1>DeletecollegeFaculty</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>collegeFacultymodel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacultyID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FacultyID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Designation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Designation)
        </dd>
    </dl>
    
    <form asp-action="DeletecollegeFaculty">
        <input type="hidden" name="FacultyID" value="@Model.FacultyID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

dotnet2/Views/collegeFaculty/DetailcollegeFaculty.cshtml
@model collegemanagementfirstproject.Models.collegeFacultymodel

@{
    ViewData["Title"] = "DetailcollegeFaculty";
}

<h1>DetailcollegeFaculty</h1>

<div>
    <h4>collegeFacultymodel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacultyID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FacultyID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Designation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Designation)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

dotnet2/Views/collegeFaculty/EditcollegeFaculty.cshtml
@model collegemanagementfirstproject.Models.collegeFacultymodel

@{
    ViewData["Title"] = "EditcollegeFaculty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>EditcollegeFaculty</h1>

<h4>collegeFacultymodel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditcollegeFaculty">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FacultyID" class="control-label"></label>
                <input asp-for="FacultyID" class="form-control" />
                <span asp-validation-for="FacultyID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Designation" class="control-label"></label>
                <input asp-for="Designation" class="form-control" />
                <span asp-validation-for="Designation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>